### ISSUE TITLE
Question - Will this package support React components as Specimens like Catalog?

### ISSUE THREAD

**Issue by azamatsmith** [LeKoArts/gatsby-remark-design-system#3]
We'd like to use this package and like the Catalog-like pattern that it follows. 

Just curious if supporting React components:
-  has been attempted
- the problems that were faced
- and if the future direction of the project includes React components

Thanks, and love the work you've done so far.

**Comment by LekoArts** [comment]
Hi!
Thank you for the commendation.

I didn't scratch that surface on purpose actually as other people asked for that and created some solutions. I'd suggest using this one:
https://www.gatsbyjs.org/packages/gatsby-remark-component/

Please tell me if it works for you, then I can add a note to the README 👍 

You can also read up on that topic here:
https://github.com/gatsbyjs/gatsby/issues/312

Generally speaking you can use any other remark plugin (that's why I didn't include the Code Specimen. Maybe also need to add that to the README):
https://www.gatsbyjs.org/plugins/?=remark

**Comment by azamatsmith** [comment]
Thanks, @LeKoArts. 

Closing the issue and will submit PR for README if I go down this road and am successful in implementing `gatsby-remark-component`
